### ISSUE TITLE
In some scenarios Monit doesn't start

### ISSUE THREAD

**Issue by richardwhiuk** [Metaswitch/clearwater-monit#44]
With the following lines in /etc/monit/monitrc

```
 set httpd port 2812 and
    use address localhost  # only accept connection from localhost
    allow localhost        # allow localhost to connect to the server and
    allow admin:monit      # require user 'admin' with password 'monit'
    allow @monit           # allow users of group 'monit' to connect (rw)
    allow @users readonly  # allow users of group 'users' to connect readonly
```

monit won't start with the following error:

```
[cw-aio]ubuntu@ec2-xx-xx-xx-x:/$ sudo /usr/bin/monit -I -c /etc/monit/monitrc
/etc/monit/monitrc:122: Erroneous network or host identifier localhost 'localhost'
```

This was seen on the All In One node during Sprint Quilava,

**Comment by eleanor-merry** [comment]
This was because all the non-clearwater-infrastructure added entries in /etc/hosts had been deleted - in particular `127.0.0.1 localhost`. Adding this back fixed this up.

This is probably because clearwater-infrastructure tried to alter /etc/hosts when the node had run out of disk space.

In https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/hostname#L40 the script copies the current contents of /etc/hosts to a temporary file (minus the edited bits). This can fail if the node is out of disk space, but the script doesn't check for success.

It then writes some more values to the temp file (https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-infrastructure/usr/share/clearwater/infrastructure/scripts/hostname#L51), then copies that back to /etc/hosts. If this succeeds (as say a log cleanup script has cleared some space), then we end up in situation of only having the clearwater-infrastructure entries in the file.
